### ISSUE TITLE
Słowo wstępne

### ISSUE THREAD

**Issue by BERENZ** [eRum2016/Book-of-abstracts#6]
Kto mógłby mi pomóc ułożyć słowo wstępne? Może być po polsku, damy do tłumaczenia w j. angielskim.

**Comment by zjanna** [comment]
Dear participant,

We welcome you to the European R users meeting \textit{eRum 2016} which will be held at the Poznan University of Economics and Business, Poland, on 13-14 October 2016.

In addition, a series of short training courses will take place on the day before to the start of the Conference (12 October 2016).

Conferences succeed through the contributions of their participants. So we are happy to offer you an interesting and broad program. Due to the overwhelming response of our call for papers most of sessions are parallel. The Conference aims to cover relevant and innovative topics including: Bayesian Statistics, Bioinformatics, Economics, Finance and Insurance, Industrial Applications, Spatial Statistics and many more.

Besides the scientific program, the eRum Conference will be held in the familiar atmosphere. There will be a poster session on Thursday evening with a Welcome paRty. Saturday sightseeing will lead us to the most famous places in Poznan. Note also the excellent opportunity for further cultural activities in Poznan.

The Conference website offers information on the conference venue, accommodation, short courses and leisure-time activities as well as deadlines for submission of papers.

**Comment by zjanna** [comment]
zmieniajcie jak widzicie bledy...

**Comment by BERENZ** [comment]
Możecie wprowadzać zmiany również online - https://www.overleaf.com/6439171rpqgpf#/21711441/

**Comment by BERENZ** [comment]
Po zmianach Grzegorza.

Welcome to the European R users meeting \textit{eRum 2016} which will be held at Poznan University of Economics and Business, Poland, on 13-14 October 2016.

In addition, a series of short training courses will take place the day before the start of the Conference (12 October 2016).

Conferences succeed through the contributions of their participants. So we are happy to offer you an interesting and broad program. Owing to the overwhelming response to our call for papers, most sessions will run in parallel. The Conference aims to cover relevant and innovative topics including: Bayesian Statistics, Bioinformatics, Economics, Finance and Insurance, Industrial Applications, Spatial Statistics and many more.

Besides the scientific program, the eRum Conference will be held in a familial atmosphere. There will be a poster session on Thursday evening with a Welcome paRty. The Saturday sightseeing tour will take us to the most famous places in Poznan. Your stay in Poznan will be an opportunity to enjoy other cultural activities in Poznan.

The Conference website provides information about the conference venue, accommodation, short courses and leisure-time activities as well as deadlines for submission of papers.

**Comment by BERENZ** [comment]
@Nowosad @mkdyderski proszę dodajcie to słowo wstępu do abstraktu https://www.overleaf.com/6439171rpqgpf#/21711441/

**Comment by Nowosad** [comment]
Już się robi;) - jeżeli ktoś coś jeszcze zmieni w tym tekście - to dajcie znać.

**Comment by Nowosad** [comment]
Done

**Comment by BERENZ** [comment]
@Nowosad proszę wyjustuj tekst :)

**Comment by Nowosad** [comment]
Done
